"""Update Pos Order

Revision ID: 06dc60045504
Revises: 3d9340c07639
Create Date: 2021-07-23 20:22:17.769693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06dc60045504'
down_revision = '3d9340c07639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_template')
    op.drop_table('jinja_template')
    op.create_foreign_key(None, 'ab_user', 'company', ['company_id'], ['id'])
    op.drop_column('document_template', 'tmpl')
    op.add_column('pos_config', sa.Column('is_multiple_payment', sa.Boolean(), nullable=True))
    op.drop_column('product_product', 'categ_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_product', sa.Column('categ_id', sa.INTEGER(), nullable=True))
    op.drop_column('pos_config', 'is_multiple_payment')
    op.add_column('document_template', sa.Column('tmpl', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'ab_user', type_='foreignkey')
    op.create_table('jinja_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('doc_template',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('templ', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
