"""Initial migration.

Revision ID: 3d9340c07639
Revises: 
Create Date: 2021-07-20 14:31:06.815877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9340c07639'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ab_user', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key('None', 'ab_user', 'company', ['company_id'], ['id'])
    op.add_column('jinja_template', sa.Column('templ', sa.Text(), nullable=True))
    op.drop_column('product_product', 'categ_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_product', sa.Column('categ_id', sa.INTEGER(), nullable=True))
    op.drop_column('jinja_template', 'templ')
    op.drop_constraint(None, 'ab_user', type_='foreignkey')
    op.drop_column('ab_user', 'company_id')
    # ### end Alembic commands ###
