"""empty message

Revision ID: 47aab57dc761
Revises: 8b14e2567e9f
Create Date: 2021-08-22 23:14:14.204049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47aab57dc761'
down_revision = '8b14e2567e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', flask_appbuilder.models.mixins.ImageColumn(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_product', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
