"""empty message

Revision ID: 54e14fdad2c3
Revises: c0083ec90bb7
Create Date: 2021-08-20 09:37:57.187926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e14fdad2c3'
down_revision = 'c0083ec90bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_order', schema=None) as batch_op:
        batch_op.create_foreign_key('partner_id', 'res_partner', ['partner_id'], ['id'])

    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.drop_column('barcode')

    with op.batch_alter_table('pos_order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
