"""empty message

Revision ID: 6af5afca5b46
Revises: 9b7b2a1e0afa
Create Date: 2021-07-30 11:55:33.855495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af5afca5b46'
down_revision = '9b7b2a1e0afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_sequence', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['prefix'])
        batch_op.create_unique_constraint(None, ['suffix'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_sequence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
