"""empty message

Revision ID: 8b14e2567e9f
Revises: f5b2eb5e0441
Create Date: 2021-08-22 18:21:14.794061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b14e2567e9f'
down_revision = 'f5b2eb5e0441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_config', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
