"""empty message

Revision ID: 8bd33c3c15c3
Revises: 942ff523c03e
Create Date: 2021-08-22 10:37:38.942336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd33c3c15c3'
down_revision = '942ff523c03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_floor_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('None', 'pos_floor', ['pos_floor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pos_floor_id')

    # ### end Alembic commands ###
