"""empty message

Revision ID: 942ff523c03e
Revises: 54e14fdad2c3
Create Date: 2021-08-20 10:14:09.311340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942ff523c03e'
down_revision = '54e14fdad2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.create_unique_constraint('barcode', ['barcode'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('res_partner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
