"""empty message

Revision ID: 9b7b2a1e0afa
Revises: b880e5b78106
Create Date: 2021-07-30 11:45:59.992646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7b2a1e0afa'
down_revision = 'b880e5b78106'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_sequence', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['suffix'])
        batch_op.create_unique_constraint(None, ['prefix'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ir_sequence', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
