"""empty message

Revision ID: b880e5b78106
Revises: 8d03f21b6003
Create Date: 2021-07-30 09:15:00.517994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b880e5b78106'
down_revision = '8d03f21b6003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('templ_heaeder', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('templ_footer', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_template', schema=None) as batch_op:
        batch_op.drop_column('templ_footer')
        batch_op.drop_column('templ_heaeder')

    # ### end Alembic commands ###
