"""empty message

Revision ID: c0083ec90bb7
Revises: 52aa0a83b6b8
Create Date: 2021-08-16 11:04:24.068499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0083ec90bb7'
down_revision = '52aa0a83b6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pos_table', schema=None) as batch_op:
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
