"""empty message

Revision ID: dcfdf35e7fa7
Revises: 06dc60045504
Create Date: 2021-07-23 20:23:39.567092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcfdf35e7fa7'
down_revision = '06dc60045504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ab_user', 'company', ['company_id'], ['id'])
    op.drop_column('document_template', 'tmpl')
    op.add_column('pos_config', sa.Column('is_multiple_payment', sa.Boolean(), nullable=True))
    op.drop_column('product_product', 'categ_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_product', sa.Column('categ_id', sa.INTEGER(), nullable=True))
    op.drop_column('pos_config', 'is_multiple_payment')
    op.add_column('document_template', sa.Column('tmpl', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'ab_user', type_='foreignkey')
    # ### end Alembic commands ###
