"""empty message

Revision ID: f5b2eb5e0441
Revises: 8bd33c3c15c3
Create Date: 2021-08-22 10:43:25.219496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b2eb5e0441'
down_revision = '8bd33c3c15c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_pos_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_pos_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.Column('pos_floor_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['pos_floor_id'], ['pos_floor.id'], name='pos_floor'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
